### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by 1amir-talaat** [tuzumkuru/notion-imdb-movielist-update#1]
when I use the script, this error gets to me.
Traceback (most recent call last):
  File "C:\Users\amir talaat\Desktop\notion\notion watchlist\main.py", line 208, in <module>
    DATABASE_ID = get_database_id_from_url(NOTION_DATABASE_URL)
  File "C:\Users\amir talaat\Desktop\notion\notion watchlist\main.py", line 179, in get_database_id_from_url
    result = re.search(r"notion\.so/[^/]+/(\w+)", database_url).group(1)
  File "C:\Users\amir talaat\AppData\Local\Programs\Python\Python310\lib\re.py", line 200, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object

**Comment by tuzumkuru** [comment]
How are your environment variables NOTION_DATABASE_URL and NOTION_DATABASE_NAME set? It looks like there is an error with them. For NOTION_DATABASE_URL you should input the full web address of your database page.

**Comment by tuzumkuru** [comment]
no responses, so closing the issue.
